# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import FedAsynCS_pb2 as proto_dot_FedAsynCS__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/FedAsynCS_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningStub(object):
    """The Federated Learning Service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGlobalModel = channel.unary_unary(
                '/fedac_cs.FederatedLearning/GetGlobalModel',
                request_serializer=proto_dot_FedAsynCS__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_FedAsynCS__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.SubmitUpdate = channel.unary_unary(
                '/fedac_cs.FederatedLearning/SubmitUpdate',
                request_serializer=proto_dot_FedAsynCS__pb2.ClientUpdate.SerializeToString,
                response_deserializer=proto_dot_FedAsynCS__pb2.Ack.FromString,
                _registered_method=True)


class FederatedLearningServicer(object):
    """The Federated Learning Service definition.
    """

    def GetGlobalModel(self, request, context):
        """Client calls this to download the latest global model and correction term.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitUpdate(self, request, context):
        """Client calls this to upload their compressed, corrected update.
        Returns a status acknowledgment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=proto_dot_FedAsynCS__pb2.Empty.FromString,
                    response_serializer=proto_dot_FedAsynCS__pb2.ModelResponse.SerializeToString,
            ),
            'SubmitUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitUpdate,
                    request_deserializer=proto_dot_FedAsynCS__pb2.ClientUpdate.FromString,
                    response_serializer=proto_dot_FedAsynCS__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedac_cs.FederatedLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedac_cs.FederatedLearning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearning(object):
    """The Federated Learning Service definition.
    """

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedac_cs.FederatedLearning/GetGlobalModel',
            proto_dot_FedAsynCS__pb2.Empty.SerializeToString,
            proto_dot_FedAsynCS__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedac_cs.FederatedLearning/SubmitUpdate',
            proto_dot_FedAsynCS__pb2.ClientUpdate.SerializeToString,
            proto_dot_FedAsynCS__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
