# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/FedAsynCS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/FedAsynCS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/FedAsynCS.proto\x12\x08\x66\x65\x64\x61\x63_cs\"\x07\n\x05\x45mpty\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"R\n\rModelResponse\x12\x10\n\x08round_id\x18\x01 \x01(\x05\x12\x0f\n\x07weights\x18\x02 \x03(\x02\x12\x1e\n\x16global_control_variate\x18\x03 \x03(\x02\"\xf5\x01\n\x0c\x43lientUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x1b\n\x13\x62\x61se_model_round_id\x18\x02 \x01(\x05\x12\x1a\n\x12\x63ompressed_payload\x18\x03 \x01(\x0c\x12\x18\n\x10measurement_seed\x18\x04 \x01(\x05\x12\x1b\n\x13original_vector_len\x18\x05 \x01(\x05\x12\x1d\n\x15\x63ompressed_vector_len\x18\x06 \x01(\x05\x12\x1d\n\x15\x64\x65lta_control_variate\x18\x07 \x03(\x02\x12\x13\n\x0bnum_samples\x18\x08 \x01(\x05\x12\x0f\n\x07is_1bit\x18\t \x01(\x08\x32\x8a\x01\n\x11\x46\x65\x64\x65ratedLearning\x12<\n\x0eGetGlobalModel\x12\x0f.fedac_cs.Empty\x1a\x17.fedac_cs.ModelResponse\"\x00\x12\x37\n\x0cSubmitUpdate\x12\x16.fedac_cs.ClientUpdate\x1a\r.fedac_cs.Ack\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.FedAsynCS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_ACK']._serialized_start=44
  _globals['_ACK']._serialized_end=83
  _globals['_MODELRESPONSE']._serialized_start=85
  _globals['_MODELRESPONSE']._serialized_end=167
  _globals['_CLIENTUPDATE']._serialized_start=170
  _globals['_CLIENTUPDATE']._serialized_end=415
  _globals['_FEDERATEDLEARNING']._serialized_start=418
  _globals['_FEDERATEDLEARNING']._serialized_end=556
# @@protoc_insertion_point(module_scope)
