# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/FedCS.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/FedCS.proto\x12\x08\x66\x65\x64learn\"\x1c\n\tModelFile\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x1c\n\tModelFlat\x12\x0f\n\x07\x63ontent\x18\x01 \x03(\x02\" \n\rModelFlatSign\x12\x0f\n\x07\x63ontent\x18\x01 \x03(\x08\"\x15\n\x06Status\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\x19\n\x17\x46\x65\x64\x65ratedLearningServer2\xa3\x04\n\x17\x46\x65\x64\x65ratedLearningClient\x12\x34\n\tSendModel\x12\x13.fedlearn.ModelFile\x1a\x10.fedlearn.Status\"\x00\x12\x37\n\rStartTraining\x12\x0f.fedlearn.Empty\x1a\x13.fedlearn.ModelFile\"\x00\x12\x35\n\x07SignSGD\x12\x0f.fedlearn.Empty\x1a\x17.fedlearn.ModelFlatSign\"\x00\x12\x35\n\x0bPhase1_CSFL\x12\x0f.fedlearn.Empty\x1a\x13.fedlearn.ModelFlat\"\x00\x12<\n\x0ePhase1_1B_CSFL\x12\x0f.fedlearn.Empty\x1a\x17.fedlearn.ModelFlatSign\"\x00\x12\x34\n\x06Phase2\x12\x0f.fedlearn.Empty\x1a\x17.fedlearn.ModelFlatSign\"\x00\x12>\n\x13UpdateClientWeights\x12\x13.fedlearn.ModelFlat\x1a\x10.fedlearn.Status\"\x00\x12\x46\n\x17UpdateClientWeightsSign\x12\x17.fedlearn.ModelFlatSign\x1a\x10.fedlearn.Status\"\x00\x12/\n\tTerminate\x12\x0f.fedlearn.Empty\x1a\x0f.fedlearn.Empty\"\x00\x62\x06proto3')



_MODELFILE = DESCRIPTOR.message_types_by_name['ModelFile']
_MODELFLAT = DESCRIPTOR.message_types_by_name['ModelFlat']
_MODELFLATSIGN = DESCRIPTOR.message_types_by_name['ModelFlatSign']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
ModelFile = _reflection.GeneratedProtocolMessageType('ModelFile', (_message.Message,), {
  'DESCRIPTOR' : _MODELFILE,
  '__module__' : 'proto.FedCS_pb2'
  # @@protoc_insertion_point(class_scope:fedlearn.ModelFile)
  })
_sym_db.RegisterMessage(ModelFile)

ModelFlat = _reflection.GeneratedProtocolMessageType('ModelFlat', (_message.Message,), {
  'DESCRIPTOR' : _MODELFLAT,
  '__module__' : 'proto.FedCS_pb2'
  # @@protoc_insertion_point(class_scope:fedlearn.ModelFlat)
  })
_sym_db.RegisterMessage(ModelFlat)

ModelFlatSign = _reflection.GeneratedProtocolMessageType('ModelFlatSign', (_message.Message,), {
  'DESCRIPTOR' : _MODELFLATSIGN,
  '__module__' : 'proto.FedCS_pb2'
  # @@protoc_insertion_point(class_scope:fedlearn.ModelFlatSign)
  })
_sym_db.RegisterMessage(ModelFlatSign)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'proto.FedCS_pb2'
  # @@protoc_insertion_point(class_scope:fedlearn.Status)
  })
_sym_db.RegisterMessage(Status)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.FedCS_pb2'
  # @@protoc_insertion_point(class_scope:fedlearn.Empty)
  })
_sym_db.RegisterMessage(Empty)

_FEDERATEDLEARNINGSERVER = DESCRIPTOR.services_by_name['FederatedLearningServer']
_FEDERATEDLEARNINGCLIENT = DESCRIPTOR.services_by_name['FederatedLearningClient']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELFILE._serialized_start=31
  _MODELFILE._serialized_end=59
  _MODELFLAT._serialized_start=61
  _MODELFLAT._serialized_end=89
  _MODELFLATSIGN._serialized_start=91
  _MODELFLATSIGN._serialized_end=123
  _STATUS._serialized_start=125
  _STATUS._serialized_end=146
  _EMPTY._serialized_start=148
  _EMPTY._serialized_end=155
  _FEDERATEDLEARNINGSERVER._serialized_start=157
  _FEDERATEDLEARNINGSERVER._serialized_end=182
  _FEDERATEDLEARNINGCLIENT._serialized_start=185
  _FEDERATEDLEARNINGCLIENT._serialized_end=732
# @@protoc_insertion_point(module_scope)
